spring.application.name=eventManagementBis

spring.config.import=file:env.properties

# web
server.port=${WEB_SERVER_PORT}

# database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Jwt
spring.jwt.secret=${JWT_SECRET}
